FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
COPY apps/api/package*.json apps/api/
COPY packages/shared-types/package*.json packages/shared-types/

RUN npm ci

COPY apps/api ./apps/api
COPY packages/shared-types ./packages/shared-types
COPY tsconfig.base.json ./

RUN npm run build -w @attendance/shared-types
RUN npm run build -w @attendance/api

EXPOSE 4040

CMD ["npm", "run", "start", "-w", "@attendance/api"]
