
services:
  backend:
    image: ghcr.io/suriyanandhimalai555-prog/ems-backend:latest
    container_name: ems-backend
    restart: always
    env_file:
      - .env
    ports:
      - "4040:4040"

  frontend:
    image: ghcr.io/suriyanandhimalai555-prog/ems-frontend:latest
    container_name: ems-frontend
    restart: always
    ports:
      - "3020:80"
    depends_on:
      - backend

  worker:
    image: ghcr.io/suriyanandhimalai555-prog/ems-worker:latest
    container_name: ems-worker
    restart: always
    env_file:
      - .env
    depends_on:
      - backend
