FROM node:22-alpine AS builder

WORKDIR /app

COPY . .

# Build argument from GitHub Actions
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

RUN npm install
RUN npm run build -w frontend

FROM nginx:alpine

# Custom nginx config
COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

# React build
COPY --from=builder /app/frontend/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx","-g","daemon off;"]
