FROM node:22-alpine AS builder

WORKDIR /app

# Copy dependency manifests first for Docker cache
COPY package*.json ./
COPY frontend/package*.json frontend/
COPY apps/api/package*.json apps/api/
COPY apps/worker/package*.json apps/worker/
COPY packages/shared-types/package*.json packages/shared-types/

# Install exact locked dependencies
RUN npm ci

# Copy only source files after dependencies
COPY frontend ./frontend
COPY apps/api ./apps/api
COPY apps/worker ./apps/worker
COPY packages/shared-types ./packages/shared-types
COPY tsconfig.base.json ./

# Build frontend
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

RUN npm run build -w frontend


FROM nginx:alpine

COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/frontend/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
